# **Demonstration Video Problems**

**Problem-1**:

In [1]:
import numpy as np
arr = np.array([3, 8, 12, 6, 4])
print("Array: ", arr)
print("Dimension: ", arr.ndim)
print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

Array:  [ 3  8 12  6  4]
Dimension:  1
Shape:  (5,)
Size:  5
Data Type:  int64


**Problem-2**:

In [3]:
import numpy as np
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Problem-3**:

In [4]:
import numpy as np
arr_zeros = np.zeros((2,3), dtype=int)
arr_ones = np.ones((2,3))
print("Zeros array:\n", arr_zeros)
print("Ones array:\n", arr_ones)

Zeros array:
 [[0 0 0]
 [0 0 0]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]


**Problem-4**:

In [5]:
import numpy as np
arr1 = np.array([5, 10, 15])
arr2 = np.array([2, 4, 6])
print("Addition: ", arr1+arr2)
print("Subtraction: ", arr1-arr2)
print("Multiplication: ", arr1*arr2)
print("Division: ", arr1/arr2)

Addition:  [ 7 14 21]
Subtraction:  [3 6 9]
Multiplication:  [10 40 90]
Division:  [2.5 2.5 2.5]


**Problem-5**:

In [6]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Problem-6**:

In [7]:
import numpy as np
print("Flatten: ")
flat=arr.flatten()
print(flat)

Flatten: 
[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Problem-7**:

In [8]:
import numpy as np
arr = np.array([2, 4, 6, 8, 10])
print("Max: ", np.max(arr))
print("Min: ", np.min(arr))
print("Mean: ", np.mean(arr))
print("Variance: ", np.var(arr))
print("Std Dev: ", np.std(arr))

Max:  10
Min:  2
Mean:  6.0
Variance:  8.0
Std Dev:  2.8284271247461903


**Problem-8**:

In [9]:
import numpy as np
arr1 = np.array([[10, 20, 30], [40, 50, 60]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2
print(result)

[[11 22 33]
 [41 52 63]]


**Problem-9**:

In [10]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
sub = arr[1:,1:]
print("Extracted: ")
print(sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Extracted: 
[[5 6]
 [8 9]]


**Problem-10**:

In [11]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]
