# **Numpy**

NumPy (Numerical Python) is the foundational library that performs lightning-fast math operations on massive datasets. Behind the scenes, almost every other ML library (including Pandas and Scikit-Learn) relies on NumPy arrays.

## **The CoreConcept: The N-Dimensional Array *(ndarray)***



*   Unlike standard Python lists, NumPy arrays require all data to be of the same type (usually numbers).

*   This single-type requirement makes them incredibly fast and memory-efficient.




## **Vectorization & Broadcasting**



*   This is the most critical NumPy concept for ML.
*   You do not use ***for*** loops in NumPy.
*   Instead, you apply mathematical operations directly to the entire array at once, which is known as Vectorization.



## **Essential NumPy Operations Cheat Sheet**

### **Phase-1: The Math Engine (Basics)**

#### **Shape & Size *(array_name.shape)***

ML algorithms are incredibly strict about the dimensions (shape) of the data you feed them.

In [15]:
import numpy as np
data = np.array([[10,20,30], [40,50,60]])
data.shape

(2, 3)

#### **Reshaping *(array_name.reshape)***

You often need to flatten images (2D to 1D) or reshape data batches to fit a neural network.

In [16]:
import numpy as np
# A 2x2 grid of image pixels

image = np.array([[155, 200], [100, 50]])

# Flattening it into a 1D array of 4 pixels
# (Pass '3' or '5' in reshape() argument and find out what's happening and why it's happening!)

flat_image = image.reshape(4)
flat_image

array([155, 200, 100,  50])

#### **Basic Stats *(np,mean(), np.std(), np.sum())***

Used heavily in feature scaling and normalizing your data so your models learn effectively.

In [17]:
import numpy as np
prices = np.array([100,200,300,400])
print ("Average = ", np.mean(prices))
print ("Total = ", np.sum(prices))
print ("Standard Deviation = ", np.std(prices))

Average =  250.0
Total =  1000
Standard Deviation =  111.80339887498948


#### **Zeroes & Ones *(np.zeros(), np.ones())***

Used to initialize weights in algorithms or to create dummy datasets for testing.

In [18]:
import numpy as np

# Creating a 3x3 matrix filled with zeroes
dummy_data = np.zeros((3,3))
dummy_data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### **Phase-2: The Missing Essentials**

#### **Matrix Multiplication *(np.dot(A,B))***

The absolute core of deep learning.

In [19]:
import numpy as np

features = np.array([2,5]) # e.g., bedrooms, age of house
weights = np.array([100, -5]) # e.g., value per bedroom, penalty per year

# Multiply features by weights to get a price prediciton
prediction = np.dot(features, weights)
prediction

np.int64(175)

#### **Combining Arrays *(np.concatenate)***

Used constantly to merge your feature data (X) with your labels (y), or to combine different batches of data together. \
\
\
\
\
**All the input arrays must have same number of dimensions.**

In [25]:
import numpy as np

batch_1 = np.array([1,2,3])
batch_2 = np.array([4,5,6])

#Sticking them together end-to-end
full_dataset = np.concatenate((batch_1, batch_2))
full_dataset

array([1, 2, 3, 4, 5, 6])

#### **Finding the Winner *(np.argmax())***

Returns the index of the highest value. If your model outputs probabilities for different categories, this tells you which category the model thinks is the correct answer.\
\
\
\
\
\
\
***Try keeping two probabilites same***

In [29]:
import numpy as np

# Probabilities output by an AI: [Cat, Dog, Bird]
Probabilities = np.array([0.1,0.1,0.8])

# Which index is the highest?
prediction_index = np.argmax(Probabilities)

prediction_index

np.int64(2)

#### **Randomization *(np.random.seed(), np.random.rand())***

Used to randomly shuffle your training data (so the model doesn't memorize the order) or to initialize starting weights for a neural network.

In [31]:
import numpy as np

# Locking the seed ensures we get the same "random" numbers every time
np.random.seed(42)

# Generate 3 random weights between 0 and 1
random_weights = np.random.rand(3)

random_weights

array([0.37454012, 0.95071431, 0.73199394])

**What is *np.random.seed(42)***

Computers cannot generate truly random numbers; they use math formulas to create "pseudo-random" numbers.

A seed is the starting point for that math formula.

By explicitly setting the seed to 42, you are telling the computer: "Start your random sequence from this exact specific point."

Why this matters for ML: When you build a model and it gets 95% accuracy, you want to be able to run the code again tomorrow and get the exact same result. If you don't lock the seed, your initial weights will change every time you run the script, making it impossible to debug or share your work reliably. (Note: The number 42 is just a long-standing programmer joke from 'The Hitchhiker's Guide to the Galaxy'. You could use 1, 100, or 999—as long as you keep it consistent).

**What is *np.random.rand(3)***

you are calling the rand() function from NumPy's random module.

The (3) tells NumPy the shape of the array you want. In this case, a 1-Dimensional array containing 3 items.

The rand() function specifically generates numbers strictly between 0 and 1.

Why this matters for ML: Neural networks start as a blank slate. Before they can learn, their connections (weights) need to be initialized with small, random numbers so the math algorithms have a starting point to optimize from.

#### **Memory Management *(array_name.astype())***

Converting data from heavy 64-bit floats down to 32-bit floats is a standard trick to train models faster and save memory.

In [33]:
import numpy as np
heavy_data = np.array([1.1,2.2,3.3])
print(heavy_data.dtype)   # Output: float64 (Uses 64 bits per number)
print(heavy_data)

# Compressing to 32 bits to save RAM
light_data = heavy_data.astype('float32')

print(light_data.dtype)   # Output: float32
print(light_data)

float64
[1.1 2.2 3.3]
float32
[1.1 2.2 3.3]
